### ISSUE TITLE
Sara's opinions

### ISSUE THREAD

**Issue by ColemanGariety** [sarajs/Sara#18]
A question for @mkgh.

When building a Sara app with an adapter for a view framework, should Sara let you write baed on the idioms of the framework (like angularjs)? In other words, should you write an AngularJS router/view (`$routeProvier(function () {}`) and let Sara proxy that into something isomorphic.

OR

When building a Sara app with an adapter for a view framework, should Sara make you write her own way of doing things, and then she'll proxy that to the adapter. In other words, should you be writing NodeJS-style `app.get()`, `app.post()` and let Sara proxy that to Angular?

The common use of an "adapter" would be the second one, but do we want to force people to do it our way? How many opinions should Sara have? Why not just bake Facebook's react into SaraJS and keep it behind the scenes? That wouldn't be NodeJS-like, but what would?

**Comment by topokel** [comment]
Well the app.get, app.post isn't 'NodeJs-like' per say, rather it's how connect did it and it's how everybody followed. I don't think it's the defacto way to do web servers. What people would probably really want from a truly NodeJs-like web server framework is extensibility (and who's to say they DON'T want an endless pile of callbacks, really), and there's a lot of really interesting chances for people to extend their respective MVC's style of doing things (which is less likely to change than individual approaches) in an isomorphic environment. I don't see Sara as a full on framework anymore, since we've taken a good look at our priorities. It seems to be more like our little kernel to simplify using frontend heavy web apps with MVC frameworks and databases and you've definitely built a lot of exciting JavaScript to do just that. 

That being said, adapters could be whatever the fuck they want to be because they're plug in, unplug, from the main repository. If Sara's api stays generally the same, there's a good chance we could have a lot of good adapters that look at this from different perspectives and people might find themselves rewriting their own adapters. From my perspective, at the least, the first situation seems to be the most beneficial in an MVC development environment. It's also worth thinking about how people would go about routing their views from the server, though.

**Comment by ColemanGariety** [comment]
@mkgh the issue is that there are large portions of these frameworks that don't fit well into the isomorphic world. Sara's job shouldn't be to coerce non-isomorphic idioms into isomorphic ones.

Routing: The AngularJS router doesn't fit in well on the server since it has no understanding of beginning or ends to requests, it just feeds HTML elements into a container on click, which is a sorry excuse for a router. No client-side routers work on the server for this reason. A job for Sara? Absolutely.

Templating: Angular's templating works _okay_ on the server, with the exception that an application's state can't be resumed, but you can get around that pretty easily. React, Ember, Rivets.js, and Ractive, on the other hand, work great for server-side templating. A job for Sara? Really not sure about this one since I haven't explored using web sockets to synchronize. What do you think?

Data: AngularJS's $cacheFactory is just key/value, so relational databases go out the window. This makes Angular bad for server-side data storage. Ember Data, while relational, is highly unstable and leans on AJAX so much it would be hard to use as an isomorphic data store. A job for Sara? I think so.

Logging: Not many front-end frameworks dabble in this. Ember does a good job. I think this is a place where Sara can really shine.

What components of a web application should Sara handle now?

**Comment by ColemanGariety** [comment]
@mkgh a simpler way to put it:

Should Sara be an alternative framework to Ember/Angular with a beautiful, isomorphic API?

Or should it be a library for coercing non-isomorphic APIs like Angular and Ember into isomorphic ones?

**Comment by ColemanGariety** [comment]
I've come to a consensus:

Sara.js will have to handle routing herself to be truly isomorphic, so she should not be coupled with frameworks like Ember.js or AngularJS since they have too many routing opinions.

You should, however, be able to use Sara with any view layer or database, and adapters will need to be made for those. Additionally, Sara will come with her own view layer based on React's, and a RethinkDB (or NeDB?) adapter built in.

The purpose of the view adapters is so developers can use existing templates wether they be in Handlebars or EJS or Jade or whatever. And database adapters are a must, especially since Sara's ORM will be so pretty.

It's important that with these decisions, Sara doesn't lose sight of Node's philosophy: loosely coupled components that work together, not on top of each other.

**Comment by topokel** [comment]
I am totally in favor of everything you just said.
