### ISSUE TITLE
Sandbox the routes with contextify

### ISSUE THREAD

**Issue by ColemanGariety** [sarajs/Sara#57]
Today I learned about the `vm` module. Right now the window object is passed into the route. This parameter can be removed, and `runInNewContext` can be used to execute the route with the window object in the scope.

**Comment by ColemanGariety** [comment]
Would most likely fix #56

**Comment by topokel** [comment]
You might want to take a peek at [brianmcd/contextify](https://github.com/brianmcd/contextify) for playing around with; it creates a true v8 context instead of a virtual one for added security between child executed scripts, as well as some other crazy magic that I don't fully understand. Note brianmcd/contextify#82 but I have no idea how far along that'll get.

**Comment by ColemanGariety** [comment]
jsdom already uses contextify, so that might be a better option.

**Comment by topokel** [comment]
Okay I'm silly and don't read. It's in Node v0.12 but nothing before that.

**Comment by ColemanGariety** [comment]
@mkgh isn't it an npm package? It's written in C, and I'm not exactly sure how it differs from `vm`

**Comment by topokel** [comment]
It works totally similar to `vm`, so the functionality was ported into `vm` on top of the v0.12 api for it. Stable version of node is only up to v0.10 so there's no need to worry about it quite yet

**Comment by ColemanGariety** [comment]
@mkgh I'm running 0.10.24 and have vm and it works

**Comment by topokel** [comment]
https://github.com/brianmcd/contextify#requirevm-vs-contextify
